### ISSUE TITLE
Unable to run `cabal install`

### ISSUE THREAD

**Issue by kd8drx** [project-monolith/monolith-backend#16]
On Mac OS X 10.10.3, when running Cabal Install, I get the following output:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: monolith-backend-0.1.0.0 (user goal)
next goal: base (dependency of monolith-backend-0.1.0.0)
rejecting: base-4.7.0.2/installed-99f... (conflict: monolith-backend =>
base>=4.8 && <4.9)
rejecting: base-4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0,
4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0,
4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed
instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```
Any thoughts?

**Comment by mdunsmuir** [comment]
My first thought is that I may have left a necessary step out of the instructions: you might have to run `cabal update` to download the package list for a fresh install of cabal.

Also, while we're on the subject, I recommend using `cabal install -j --only-dependencies` (with the j), which uses more than one core for the build.

**Comment by mdunsmuir** [comment]
instructions in README updated to address what was going wrong here.
